# Reflection

When I was making the decision to enroll in this class I was thinking about discrete math as a tool for other courses, mainly computer science and statistics. I wanted to understand some of the more complicated theory in these fields, and I had a vague sense of what type of mathematical background I had to aim for. Now, I realize that I stopped looking at math through the lens of a first year student coming to Multivariable Calculus and rushing into Linear Algebra the second semester. Instead, I now regard math as a natural extension to my way of thinking. Without meaning to sound too dramatic, math -- and specifically proof writing -- has given me an application to some of the formal argumentation that I had learned in my philosophy logic class.

In the beginning of the semester I regarded proofs as building blocks that were created and then reused to form more complex structures and arguments. This was not a bad idea. However, this changed somewhat throughout the semester. Now, I regard proofs as tangible examples of the growth of humanity, an account of our progress. Math is in every other science. To realize that every proof that we studied and reproduced was a careful addition to Man's body of knowledge was humbling. We could go over a proof in class that had taken years to be originally formulated. We studied proofs and learned how to write them, but it somehow did not feel like creating anymore. I have come to the view that the proofs were already out there, they always have, but only after we take the next leaps do we consider ourselves able to absorb the result into our huge body of knowledge and call it ours, and possibly name it after someone of of us.

For all purposes, proofs are contracts with ourselves. A proof leads to trust in the claim. Some of the problems people struggled centuries ago are now solved and in turn, newer and more complicated problems are discovered. Students like me can catch up to centuries of knowledge by looking over these proofs, testaments of human achievement. 

Taking a less dramatic tone now, I think that proofs have given me the ability to understand that there are always many logical steps that follows from a situation, but only the careful selection of these steps will logically lead to the claim where I want to go. Not only in mathematics, but in writing, speech, programming, and others. Problems can be solved with a finite amounts of techniques because of the patterns they exhibit, and simple rules can tackle complexity. This is incredibly important for me because I like tackling complexity in the computer science field. My ability to take a problem and abstract it away matured as I was taking this course, and frequently, there would be "Ahhh" moments where I would understand what my professors in Linear Algebra or Multivariable where trying to say but I was not able to understand then. 

Math is not my field. That does not mean that I cannot enjoy its benefits, nor that I have to stay away from it. Learning about proof techniques, mathematical results, and proof writing open doors to other mathematics that I will now be able to read and comprehend. 