# Proof By Cases (Triangle Inequality)

\begin{thm}[{\tt The Triangle Inequality}]
For each pair of real numbers $x$ and $y$, one has that:
\[
|x + y|\leq |x| + |y|.
\]
\end{thm}

---

## Why this proof? 

The reason this proof is included is that the Triangle Inequality is the clearest example of the proof by cases technique. The way that the proof generally follows from the definition of the absolute value makes cases clear and it is easy to see they are exhaustive. Additionally, I thought that it was important that the fourth case does not need to be proven because it is the same as the third case but with the variables switched. 

The first time I did the proof I was not able to write it down, and when I had it in the homework I did not end up feeling comfortable about it. Thus, revisiting this proof and understanding what is going on, as well as revisiting the proof technique used here, was important as the course closed off. 

---

\begin{proof}
We proceed by cases.


\textbf{Case 1:} $x\geq 0$ and $y \geq 0.$

Note that by the definition of absolute value and since $x \geq 0$ and $y \geq 0$, we have that $|x| = x$ and $|y| = y$ and $|x + y| = x + y$ (since $x + y \geq 0$). 

Thus it follows that $|x + y| \leq |x| + |y|$ (since $|x + y| = |x| + |y|$).


\textbf{Case 2:} $x < 0$ and $y < 0.$

Note that by the definition of absolute value and since $x < 0$ and $y < 0$, we have that $|x| = -x$ and $|y| = -y$ and $|x + y| = - (x + y) = -x - y$ (since $x + y < 0$). 

Thus it follows that $|x + y| \leq |x| + |y|$ (since $|x + y| = |x| + |y|$).


\textbf{Case 3:} $x\geq 0$ and $y \geq 0.$

Note that by the definition of absolute value and since $x \geq 0$ and $y < 0$, we have that $|x| = x$ and $|y| = -y$. Now we need to consider two subcases in which $|x + y|$ can satisfy $|x + y| \geq 0$ or $|x + y| < 0$. 

Suppose that $|x + y| \geq 0$. By the definition of absolute value it follows that $|x + y| = x + y$. Note that $ x - y \geq x + y$ because y is negative. By substituting we get that $|x + y| \leq |x| + |y|$.

Now suppose that $|x + y| < 0$. Observe that $|x + y| \leq x$. Since y is negative we have that $|x + y| < x - y$. After substituting equivalent values we have that $|x + y| \leq |x| + |y|$.

Since in Case 3 we have that $x$ and $y$ are arbitrary, we have exhausted the cases and we have that  $|x + y| \leq |x| + |y|$ for all $\mathbb{R}$.

\end{proof}

---

## Reflection

Looking back at the original version of this proof I can see that I have clearly improved the proof's readibility. These changes in the narrative of the proof were included because I now know that it is important for a proof to be transparent to a new reader as well as correct. 

I changed the cases a bit in order to make the proof technique stand out more and flow better one into the other.

---

\newpage